using System.Collections.Concurrent;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Threading.Channels;
using Azure.Core;
using Azure.Identity;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using CGSmartK.Application;
using CGSmartK.Domain;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace CGSmartK.Infrastructure;
public sealed class SmartAssistOptions { public AzureOpenAIOptions AzureOpenAI {get;set;}=new(); public SearchOptions Search {get;set;}=new(); public StorageOptions Storage {get;set;}=new(); public DocumentIntelligenceOptions DocumentIntelligence {get;set;}=new(); public KeyVaultOptions KeyVault {get;set;}=new(); public IngestionSettings Ingestion {get;set;}=new(); public RetrievalSettings Retrieval {get;set;}=new(); public McpOptions Mcp {get;set;}=new(); }
public sealed class AzureOpenAIOptions { public string Endpoint {get;set;}=""; public string ChatDeployment {get;set;}="smartassist-chat"; public string EmbeddingDeployment {get;set;}="smartassist-embedding"; public int EmbeddingDimensions {get;set;}=1536; }
public sealed class SearchOptions { public string Endpoint {get;set;}=""; public string IndexName {get;set;}="smartassist-knowledge-index"; }
public sealed class StorageOptions { public string AccountName {get;set;}="stsmartappf59ee617"; public string ContainerName {get;set;}="knowledge-documents"; }
public sealed class DocumentIntelligenceOptions { public string Endpoint {get;set;}=""; }
public sealed class KeyVaultOptions { public string Uri {get;set;}="https://kv-smartapp-f59ee617.vault.azure.net/"; }
public sealed class IngestionSettings { public int TargetTokens {get;set;}=800; public int OverlapTokens {get;set;}=120; public long MaxPdfBytes {get;set;}=20*1024*1024; public int QueueCapacity {get;set;}=20; public int BatchSize {get;set;}=50; }
public sealed class RetrievalSettings { public int TopK {get;set;}=8; public double MinimumScore {get;set;}=.55; public int MaxPerDocument {get;set;}=3; }
public sealed class McpOptions { public bool Enabled {get;set;}=false; public string? Endpoint {get;set;} public string[] AllowedTools {get;set;}=[]; public int TimeoutSeconds {get;set;}=5; public bool SyntheticDemo {get;set;}=false; }

public sealed class IngestionQueue(int capacity) : IIngestionQueue { private readonly Channel<Guid> channel=Channel.CreateBounded<Guid>(new BoundedChannelOptions(capacity){FullMode=BoundedChannelFullMode.Wait,SingleReader=true}); public ValueTask EnqueueAsync(Guid id,CancellationToken ct)=>channel.Writer.WriteAsync(id,ct); public IAsyncEnumerable<Guid> ReadAllAsync(CancellationToken ct)=>channel.Reader.ReadAllAsync(ct); }
public sealed class BlobDocumentRepository(BlobContainerClient container) : IDocumentRepository
{
    private const string MetadataPrefix="metadata/";
    public async Task SaveAsync(KnowledgeDocument d,Stream content,CancellationToken ct){ await container.CreateIfNotExistsAsync(PublicAccessType.None,cancellationToken:ct); await container.GetBlobClient(d.BlobName).UploadAsync(content,new BlobUploadOptions{HttpHeaders=new BlobHttpHeaders{ContentType="application/pdf"},Metadata=new Dictionary<string,string>{{"documentId",d.Id.ToString("N")},{"contentHash",d.ContentHash}}},ct); await UpdateMetadataAsync(d,ct); }
    public async Task<KnowledgeDocument?> GetAsync(Guid id,CancellationToken ct){ var blob=container.GetBlobClient($"{MetadataPrefix}{id:N}.json"); if(!await blob.ExistsAsync(ct)) return null; var data=await blob.DownloadContentAsync(ct); return JsonSerializer.Deserialize<KnowledgeDocument>(data.Value.Content.ToString()); }
    public async Task<KnowledgeDocument?> FindByHashAsync(string hash,CancellationToken ct){ await foreach(var item in container.GetBlobsAsync(prefix:MetadataPrefix,cancellationToken:ct)){ var id=Guid.ParseExact(Path.GetFileNameWithoutExtension(item.Name),"N"); var d=await GetAsync(id,ct); if(d?.ContentHash==hash&&d.Status!=IngestionStatus.Deleted)return d;} return null; }
    public async Task<IReadOnlyList<KnowledgeDocument>> ListAsync(CancellationToken ct){var list=new List<KnowledgeDocument>();await foreach(var item in container.GetBlobsAsync(prefix:MetadataPrefix,cancellationToken:ct)){var d=await GetAsync(Guid.ParseExact(Path.GetFileNameWithoutExtension(item.Name),"N"),ct);if(d is not null)list.Add(d);}return list.OrderByDescending(x=>x.CreatedAt).ToList();}
    public async Task UpdateMetadataAsync(KnowledgeDocument d,CancellationToken ct){ await container.GetBlobClient($"{MetadataPrefix}{d.Id:N}.json").UploadAsync(BinaryData.FromObjectAsJson(d),overwrite:true,cancellationToken:ct); }
    public async Task DeleteAsync(KnowledgeDocument d,CancellationToken ct){await UpdateMetadataAsync(d,ct);await container.GetBlobClient(d.BlobName).DeleteIfExistsAsync(cancellationToken:ct);}
}
public sealed class AzureRestClient(HttpClient http,TokenCredential credential)
{
    public async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,string scope,CancellationToken ct){var token=await credential.GetTokenAsync(new TokenRequestContext([scope]),ct);request.Headers.Authorization=new AuthenticationHeaderValue("Bearer",token.Token);return await http.SendAsync(request,HttpCompletionOption.ResponseHeadersRead,ct);}
}
public sealed class AzureDocumentExtractor(BlobContainerClient blobs, AzureRestClient rest, IOptions<SmartAssistOptions> options) : IDocumentExtractor
{
    public async Task<IReadOnlyList<ExtractedPage>> ExtractAsync(KnowledgeDocument doc,CancellationToken ct){ var endpoint=options.Value.DocumentIntelligence.Endpoint.TrimEnd('/'); using var stream=await blobs.GetBlobClient(doc.BlobName).OpenReadAsync(cancellationToken:ct); using var req=new HttpRequestMessage(HttpMethod.Post,$"{endpoint}/documentintelligence/documentModels/prebuilt-layout:analyze?api-version=2024-11-30"){Content=new StreamContent(stream)};req.Content.Headers.ContentType=new("application/pdf");using var response=await rest.SendAsync(req,"https://cognitiveservices.azure.com/.default",ct);response.EnsureSuccessStatusCode();var operation=response.Headers.Location??throw new InvalidOperationException("Document analysis operation location was absent.");for(var i=0;i<60;i++){await Task.Delay(TimeSpan.FromSeconds(2),ct);using var poll=await rest.SendAsync(new(HttpMethod.Get,operation),"https://cognitiveservices.azure.com/.default",ct);poll.EnsureSuccessStatusCode();using var json=JsonDocument.Parse(await poll.Content.ReadAsStreamAsync(ct));var status=json.RootElement.GetProperty("status").GetString();if(status=="failed")throw new InvalidOperationException("Document Intelligence could not process the PDF.");if(status=="succeeded"){var pages=new List<ExtractedPage>();foreach(var p in json.RootElement.GetProperty("analyzeResult").GetProperty("pages").EnumerateArray()){var number=p.GetProperty("pageNumber").GetInt32();var text=string.Join(' ',p.GetProperty("lines").EnumerateArray().Select(x=>x.GetProperty("content").GetString()));pages.Add(new(number,text,"Page "+number));}return pages;}}throw new TimeoutException("Document extraction exceeded the configured operation window."); }
}
public sealed class AzureEmbeddingService(AzureRestClient rest,IOptions<SmartAssistOptions> options) : IEmbeddingService
{ public async Task<float[]> EmbedAsync(string text,CancellationToken ct){var o=options.Value.AzureOpenAI;using var req=new HttpRequestMessage(HttpMethod.Post,$"{o.Endpoint.TrimEnd('/')}/openai/deployments/{Uri.EscapeDataString(o.EmbeddingDeployment)}/embeddings?api-version=2024-10-21"){Content=JsonContent.Create(new{input=text,dimensions=o.EmbeddingDimensions})};using var res=await rest.SendAsync(req,"https://cognitiveservices.azure.com/.default",ct);res.EnsureSuccessStatusCode();using var json=JsonDocument.Parse(await res.Content.ReadAsStreamAsync(ct));return json.RootElement.GetProperty("data")[0].GetProperty("embedding").EnumerateArray().Select(x=>x.GetSingle()).ToArray();}}
public sealed class AzureAnswerGenerator(AzureRestClient rest,IOptions<SmartAssistOptions> options) : IAnswerGenerator
{ public async Task<GeneratedAnswer> GenerateAsync(string question,IReadOnlyList<RetrievedPassage> context,WorkflowKind workflow,CancellationToken ct){var o=options.Value.AzureOpenAI;var supplied=string.Join("\n",context.Select(x=>$"[{x.Chunk.Id}] {x.Chunk.Text}"));var instruction=workflow switch{WorkflowKind.Summary=>"Summarize and cite.",WorkflowKind.DraftArticle=>"Create a clearly labeled DRAFT article and cite.",_=>"Answer and cite."};using var req=new HttpRequestMessage(HttpMethod.Post,$"{o.Endpoint.TrimEnd('/')}/openai/deployments/{Uri.EscapeDataString(o.ChatDeployment)}/chat/completions?api-version=2024-10-21"){Content=JsonContent.Create(new{messages=new[]{new{role="system",content=PromptSecurity.System+" Return JSON with answer and citedChunkIds."},new{role="user",content=$"{instruction}\nQuestion: {question}\nContext:\n{supplied}"}},response_format=new{type="json_object"}})};using var res=await rest.SendAsync(req,"https://cognitiveservices.azure.com/.default",ct);res.EnsureSuccessStatusCode();using var outer=JsonDocument.Parse(await res.Content.ReadAsStreamAsync(ct));var content=outer.RootElement.GetProperty("choices")[0].GetProperty("message").GetProperty("content").GetString()??"{}";using var json=JsonDocument.Parse(content);return new(json.RootElement.GetProperty("answer").GetString()??"",json.RootElement.GetProperty("citedChunkIds").EnumerateArray().Select(x=>x.GetString()??"").ToList());}}
public sealed class AzureKnowledgeIndex(AzureRestClient rest,IEmbeddingService embeddings,IOptions<SmartAssistOptions> options) : IKnowledgeIndex
{
    private SmartAssistOptions O=>options.Value; private string Base=>$"{O.Search.Endpoint.TrimEnd('/')}/indexes/{O.Search.IndexName}";
    public async Task EnsureAsync(CancellationToken ct){var schema=new{name=O.Search.IndexName,fields=new object[]{F("id","Edm.String",key:true,filterable:true),F("documentId","Edm.String",filterable:true,facetable:true),F("title","Edm.String",searchable:true),F("content","Edm.String",searchable:true),new{name="contentVector",type="Collection(Edm.Single)",searchable=true,dimensions=O.AzureOpenAI.EmbeddingDimensions,vectorSearchProfile="default-vector"},F("sourceFileName","Edm.String",searchable:true,filterable:true),F("blobName","Edm.String",filterable:true),F("pageFrom","Edm.Int32",filterable:true),F("pageTo","Edm.Int32",filterable:true),F("section","Edm.String",searchable:true),F("chunkNumber","Edm.Int32",filterable:true),F("category","Edm.String",filterable:true,facetable:true),F("classification","Edm.String",filterable:true,facetable:true),new{name="allowedGroups",type="Collection(Edm.String)",filterable=true},F("isActive","Edm.Boolean",filterable:true),F("createdAt","Edm.DateTimeOffset",filterable:true,sortable:true),F("contentHash","Edm.String",filterable:true)},vectorSearch=new{algorithms=new[]{new{name="hnsw",kind="hnsw"}},profiles=new[]{new{name="default-vector",algorithm="hnsw"}}},semantic=new{configurations=new[]{new{name="default-semantic",prioritizedFields=new{titleField=new{fieldName="title"},prioritizedContentFields=new[]{new{fieldName="content"}}}}}}};using var req=new HttpRequestMessage(HttpMethod.Put,Base+"?api-version=2024-07-01"){Content=JsonContent.Create(schema)};using var res=await rest.SendAsync(req,"https://search.azure.com/.default",ct);res.EnsureSuccessStatusCode();}
    public async Task IndexAsync(IReadOnlyList<KnowledgeChunk> chunks,CancellationToken ct){var values=chunks.Select(c=>new Dictionary<string,object?>{{"@search.action","mergeOrUpload"},{"id",c.Id},{"documentId",c.DocumentId.ToString("N")},{"title",c.Title},{"content",c.Text},{"contentVector",c.Embedding},{"sourceFileName",c.SourceFileName},{"blobName",c.BlobName},{"pageFrom",c.PageFrom},{"pageTo",c.PageTo},{"section",c.Section},{"chunkNumber",c.Ordinal},{"category",c.Category},{"classification",c.Access.Classification.ToString()},{"allowedGroups",c.Access.AllowedGroups},{"isActive",true},{"createdAt",c.CreatedAt},{"contentHash",c.ContentHash}});using var req=new HttpRequestMessage(HttpMethod.Post,Base+"/docs/index?api-version=2024-07-01"){Content=JsonContent.Create(new{value=values})};using var res=await rest.SendAsync(req,"https://search.azure.com/.default",ct);res.EnsureSuccessStatusCode();}
    public async Task DeleteDocumentAsync(Guid documentId,CancellationToken ct){using var query=new HttpRequestMessage(HttpMethod.Post,Base+"/docs/search?api-version=2024-07-01"){Content=JsonContent.Create(new{search="*",filter=$"documentId eq '{documentId:N}'",select="id",top=1000})};using var found=await rest.SendAsync(query,"https://search.azure.com/.default",ct);found.EnsureSuccessStatusCode();using var json=JsonDocument.Parse(await found.Content.ReadAsStreamAsync(ct));var value=json.RootElement.GetProperty("value").EnumerateArray().Select(x=>new Dictionary<string,object>{{"@search.action","delete"},{"id",x.GetProperty("id").GetString()!}});using var del=new HttpRequestMessage(HttpMethod.Post,Base+"/docs/index?api-version=2024-07-01"){Content=JsonContent.Create(new{value})};using var res=await rest.SendAsync(del,"https://search.azure.com/.default",ct);res.EnsureSuccessStatusCode();}
    public async Task<IReadOnlyList<RetrievedPassage>> SearchAsync(string query,float[] vector,UserAccessContext user,CancellationToken ct){using var req=new HttpRequestMessage(HttpMethod.Post,Base+"/docs/search?api-version=2024-07-01"){Content=JsonContent.Create(new{search=query,filter=SearchFilterBuilder.Build(user),top=O.Retrieval.TopK,queryType="semantic",semanticConfiguration="default-semantic",vectorQueries=new[]{new{kind="vector",vector,kNearestNeighborsCount=O.Retrieval.TopK,fields="contentVector"}},select="id,documentId,title,content,sourceFileName,blobName,pageFrom,pageTo,section,chunkNumber,category,classification,allowedGroups,createdAt,contentHash"})};using var res=await rest.SendAsync(req,"https://search.azure.com/.default",ct);res.EnsureSuccessStatusCode();using var json=JsonDocument.Parse(await res.Content.ReadAsStreamAsync(ct));var list=new List<RetrievedPassage>();foreach(var x in json.RootElement.GetProperty("value").EnumerateArray()){var access=new AccessScope(Enum.Parse<Classification>(x.GetProperty("classification").GetString()!),x.GetProperty("allowedGroups").EnumerateArray().Select(g=>g.GetString()!).ToHashSet());var c=new KnowledgeChunk(x.GetProperty("id").GetString()!,Guid.ParseExact(x.GetProperty("documentId").GetString()!,"N"),x.GetProperty("content").GetString()!,x.GetProperty("pageFrom").GetInt32(),x.GetProperty("pageTo").GetInt32(),x.GetProperty("section").GetString()!,x.GetProperty("chunkNumber").GetInt32(),x.GetProperty("title").GetString()!,x.GetProperty("sourceFileName").GetString()!,x.GetProperty("blobName").GetString()!,x.GetProperty("category").GetString()!,access,x.GetProperty("contentHash").GetString()!,x.GetProperty("createdAt").GetDateTimeOffset());list.Add(new(c,x.GetProperty("@search.score").GetDouble()));}return list;}
    private static object F(string name,string type,bool key=false,bool searchable=false,bool filterable=false,bool facetable=false,bool sortable=false)=>new{name,type,key,searchable,filterable,facetable,sortable};
}
public sealed class IngestionWorker(IIngestionQueue queue,IDocumentRepository documents,IDocumentExtractor extractor,IEmbeddingService embeddings,IKnowledgeIndex index,TokenChunker chunker,ILogger<IngestionWorker> logger) : BackgroundService
{ protected override async Task ExecuteAsync(CancellationToken stoppingToken){await foreach(var id in queue.ReadAllAsync(stoppingToken)){var doc=await documents.GetAsync(id,stoppingToken);if(doc is null)continue;try{doc.Transition(IngestionStatus.Extracting);await documents.UpdateMetadataAsync(doc,stoppingToken);var pages=await extractor.ExtractAsync(doc,stoppingToken);doc.Transition(IngestionStatus.Chunking);await documents.UpdateMetadataAsync(doc,stoppingToken);var raw=chunker.Chunk(pages);doc.Transition(IngestionStatus.Embedding);await documents.UpdateMetadataAsync(doc,stoppingToken);var chunks=new List<KnowledgeChunk>();for(var i=0;i<raw.Count;i++){var r=raw[i];var vector=await embeddings.EmbedAsync(r.Text,stoppingToken);chunks.Add(new($"{doc.Id:N}-{i:D6}",doc.Id,r.Text,r.PageFrom,r.PageTo,r.Section,i,doc.Title,doc.OriginalFileName,doc.BlobName,doc.Category,doc.Access,doc.ContentHash,doc.CreatedAt,vector));}await index.EnsureAsync(stoppingToken);await index.IndexAsync(chunks,stoppingToken);doc.Transition(IngestionStatus.Indexed,chunks.Count);await documents.UpdateMetadataAsync(doc,stoppingToken);logger.LogInformation("Ingestion {DocumentId} completed with {ChunkCount} chunks",doc.Id,chunks.Count);}catch(Exception ex) when(ex is not OperationCanceledException){doc.Transition(IngestionStatus.Failed,failure:"A document processing dependency rejected the document.");await documents.UpdateMetadataAsync(doc,stoppingToken);logger.LogError(ex,"Ingestion {DocumentId} failed",doc.Id);}}}}
public sealed class MemoryAuditStore : IAuditStore { private readonly ConcurrentDictionary<string,OperationStatus> states=new(); public Task WriteAsync(AuditEvent e,CancellationToken ct){states[e.CorrelationId]=new(e.CorrelationId,e.Operation,e.Result,e.Timestamp,e.ItemCount);return Task.CompletedTask;} public Task<OperationStatus?> GetAsync(string id,CancellationToken ct)=>Task.FromResult(states.GetValueOrDefault(id)); }
public sealed class DisabledMcpToolClient(IOptions<SmartAssistOptions> options) : IMcpToolClient { public bool IsAvailable=>options.Value.Mcp.Enabled&&options.Value.Mcp.Endpoint is not null; public Task<string> InvokeAsync(string tool,IReadOnlyDictionary<string,string> input,UserAccessContext user,CancellationToken ct){if(!IsAvailable)throw new InvalidOperationException("External tool integration is not configured.");if(!options.Value.Mcp.AllowedTools.Contains(tool,StringComparer.Ordinal))throw new UnauthorizedAccessException("Tool is not allowlisted.");if(!user.IsAdministrator)throw new UnauthorizedAccessException();return Task.FromResult(options.Value.Mcp.SyntheticDemo?"SYNTHETIC DEVELOPMENT DATA":"Production MCP transport must be configured.");} }
public static class DependencyInjection
{ public static IServiceCollection AddSmartAssistInfrastructure(this IServiceCollection services,IConfiguration configuration,bool validateAzure=true){services.AddOptions<SmartAssistOptions>().Bind(configuration.GetSection("SmartAssist")).Validate(o=>!validateAzure||Uri.TryCreate(o.AzureOpenAI.Endpoint,UriKind.Absolute,out _),"Azure OpenAI endpoint is required.").Validate(o=>!validateAzure||Uri.TryCreate(o.DocumentIntelligence.Endpoint,UriKind.Absolute,out _),"Document Intelligence endpoint is required.").Validate(o=>!validateAzure||Uri.TryCreate(o.Search.Endpoint,UriKind.Absolute,out _),"Search endpoint is required.").ValidateOnStart();var settings=configuration.GetSection("SmartAssist").Get<SmartAssistOptions>()??new();services.AddSingleton<TokenCredential>(new DefaultAzureCredential());services.AddHttpClient<AzureRestClient>().AddStandardResilienceHandler();services.AddSingleton(new BlobServiceClient(new Uri($"https://{settings.Storage.AccountName}.blob.core.windows.net"),new DefaultAzureCredential()));services.AddSingleton(sp=>sp.GetRequiredService<BlobServiceClient>().GetBlobContainerClient(settings.Storage.ContainerName));services.AddSingleton<IDocumentRepository,BlobDocumentRepository>();services.AddSingleton<IDocumentExtractor,AzureDocumentExtractor>();services.AddSingleton<IEmbeddingService,AzureEmbeddingService>();services.AddSingleton<IKnowledgeIndex,AzureKnowledgeIndex>();services.AddSingleton<IAnswerGenerator,AzureAnswerGenerator>();services.AddSingleton<IAuditStore,MemoryAuditStore>();services.AddSingleton<IMcpToolClient,DisabledMcpToolClient>();services.AddSingleton<IIngestionQueue>(new IngestionQueue(settings.Ingestion.QueueCapacity));services.AddSingleton(new IngestionOptions(settings.Ingestion.TargetTokens,settings.Ingestion.OverlapTokens,settings.Ingestion.MaxPdfBytes,settings.Ingestion.BatchSize));services.AddSingleton(new RetrievalOptions(settings.Retrieval.TopK,settings.Retrieval.MinimumScore,settings.Retrieval.MaxPerDocument));services.AddSingleton<TokenChunker>();services.AddScoped<IKnowledgeService,KnowledgeService>();services.AddScoped<IAssistantService,AssistantService>();services.AddHostedService<IngestionWorker>();return services;} }
