<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><UserSecretsId>CGSmartK-SmartAssist-Development</UserSecretsId></PropertyGroup><ItemGroup><ProjectReference Include="../CGSmartK.Infrastructure/CGSmartK.Infrastructure.csproj"/><PackageReference Include="Microsoft.ApplicationInsights.AspNetCore"/><PackageReference Include="FluentValidation.DependencyInjectionExtensions"/></ItemGroup></Project>
